package com.sws.newtec.modules.security.entity;

// Generated 2015-2-3 10:43:00 by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "shiro_permission", catalog = "newtec")
public class Permission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1495787682343110812L;
	private String id;
	private String name;
	private Set<Role> roles = new HashSet<Role>(0);

	public Permission() {
		
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "shiro_role_permission", catalog = "newtec", joinColumns = { @JoinColumn(name = "permission_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
